version: '3.8'

services:
  webapp:
    image: cabaleirog/earthquakes-webapp:latest
    depends_on:
      - api


  api:
    image: cabaleirog/earthquakes-api:latest
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
  
  nginx:
    image: cabaleirog/earthquakes-nginx:latest
    ports:
      - 80:80
    depends_on:
      - webapp
      - api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo-mysql-secret-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080