version: '3.8'

services:
  webapp:
    build:
      context: webapp/.
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./webapp/src:/code/src

  api:
    build:
      context: api-service/.
      dockerfile: Dockerfile
    ports:
      - 5001:8000
    volumes:
      - ./api-service/djangoapi:/code
    depends_on:
      - db

  redis:
    image: redis:latest
  
  nginx:
    build:
      context: nginx/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - webapp
      - api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo-mysql-secret-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080