# Generated by Django 3.2.6 on 2021-08-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='event_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
