# Generated by Django 3.2.6 on 2021-08-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0002_alter_earthquake_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
